### ISSUE TITLE
Summarize vs GroupBy

### ISSUE THREAD

**Issue by Vishwanathkinekar** [data-forge/data-forge-ts#118]
First, It's a great library.

Now,
I am using on client-side to generate aggregations to plot charts. I have data set that has 120K rows and 8 columns. I wanted to get an average for each column. 

If I use summarize then it's taking around 6 seconds. But if I add a dummy column with the same value in each row and group it by that column and take average then it's done in less than 2 seconds. 

Am I missing anything on the usage of summarize?

Regards,
Vishwa

**Comment by ashleydavis** [comment]
Hi, thanks for the feedback.

I'd love to have a look at this and work out why there's a difference.

Are you able to submit two code examples so that I can compare it myself?

Drop zip files here, or if you'd prefer email them to me on ashley@codecapers.com.au.

Thanks

**Comment by Vishwanathkinekar** [comment]
I have sent you the code sample to your email-id.

**Comment by ashleydavis** [comment]
Thanks for that, I was hoping to have a look over the weekend but I ran out of time. I'll have a look this week.

**Comment by ashleydavis** [comment]
Thanks for the sample code.

Here's what I get running it as is:

![image](https://user-images.githubusercontent.com/625126/114825713-e9d6e100-9e09-11eb-8e00-ebf48801a865.png)

**Comment by ashleydavis** [comment]
Can you please show me the code I need to add to make this run faster?

**Comment by Vishwanathkinekar** [comment]
There are two aggregates on the same data in the code. 

1. This one is groupby  on a column groupCol(value is 1 for all the rows)

**Comment by ashleydavis** [comment]
There is one big different between these two ways of doing it.

The first way with groupBy uses only a single function per row to do this aggregation.

For the second way, with summarize, the summarize function goes column by column to apply the aggregation, so that's bound to be slower right from the start.

I'll see if there is any obvious way to make it perform better.

**Comment by ashleydavis** [comment]
I've tried different options with the code, but I haven't found anything that gives it much better performance.

I think this really because the `summarize` function is very generalised and your implementation with `groupBy` is very specific, so you have basically created your own optimised version. 

I would say use your version if performance matters.

If you can think of any way that I can improve the performance of the code please let me know and I'll reopen this issue.
