### ISSUE TITLE
Window functions do not preserve the original index

### ISSUE THREAD

**Issue by preslavrachev** [data-forge/data-forge-ts#15]
Unlike Pandas, which would always preserve the original index, data-forge seems to always create a new one, unless a few boilerplate transformations get applied. Based on a couple of years of work with Pandas, I personally find this a lot of unnecessary work. Almost all the time, when creating a new series out of a windowed version of an existing one, I would attach it as a new column to the existing data frame. This makes it easy to inspect the entire data frame down the line, comparing the values in every row.

In my opinion, preserving the original index is essential for the ease of work with data-forge. Of course, this would also require handling of NaNs, their cleaning, etc.

I would be interested to know what you think about this.

**Comment by ashleydavis** [comment]
It's up to you to preserve the index. The problem is (and you might be able to tell me how Pandas does this) that I wasn't sure which index to preserve! A window contains many indexes and you might want to preserve the first index, the middle index, the last index, or some other index!

By default the new index is an integer per window starting at 0. So window 0, window 1, window 2, etc.

Here's you you can choose which index to preserve:

```
var salesData = ... series containing amount of sales for each day ...

var weeklySales = salesData.window(7) // Group into lots of 7 (for 7 days).
    .select(window => {
        return [                    // Return index and value.
            window.lastIndex(),     // Week ending.
            window.sum()            // Total the amount sold during the week.
        ]; 
    })
    .withIndex(pair => pair[0]) // Promote index.
    .select(pair => pair[1]); // Restore values.

```
(This example is from [the guide](https://github.com/data-forge/data-forge-ts/blob/master/docs/guide.md)).

**Comment by ashleydavis** [comment]
Hope that helps! Let me know if you need anything else.
