### ISSUE TITLE
Worrying / serious bug: Data from one row being referenced in another

### ISSUE THREAD

**Issue by ralphpw** [data-forge/data-forge-ts#174]
The following bug causes subtle but very serious effects, by mixing values from one row to another. This would result in potential loss of money, credibility, or clients. I kindly request this to be resolved with priority.

```
import { DataFrame, fromCSV } from 'data-forge'

export function test() {
    var table = fromCSV(`Name,Id\r\nProduct 1,1`).concat(new DataFrame([{ Name: "Product 2", Id: 2 }]));
    var a = fromCSV(table.toCSV());
    var b = table;

    // Correct!
    //          Name,Id
    //          Product 1,1
    //          Product 2,2
    console.log( a.generateSeries({ Id: (row) => row['Id'] }).toCSV() + "\r\n");

    // Incorrect!
    //          Name,Id
    //          Product 1,2
    //          Product 2,2
    console.log( b.generateSeries({ Id: (row) => row['Id'] }).toCSV());
}

```

This bug can be replicated on data-forge version "1.10.2". This issue had been affecting many rows and columns in a pricing application, quite embarassing although fortunately I had an unexpected workaround, see code sample.

p.s. this is a great library, thank you!

**Comment by ashleydavis** [comment]
Thanks for reporting the issue. I'm happy to accept a PR for a fix to the problem if you can how to do that.

**Comment by ralphpw** [comment]
I created a working unit test, but was unable to step through it as VS Code / Run / Mocha is crashing after a frash clone & npm install. I'll try again soon.

For now, here's the unit test, to be added to the bottom of scr/test/dataframe.concat.test.ts:

```
    it('should preserve original values after concat and generateSeries', () => {
        const df1 = new DataFrame({ columnNames: ["Name", "Id"], rows: [["Row 1", 1]] });
        const df2 = new DataFrame({ columnNames: ["Name", "Id"], rows: [["Row 2", 2]] });

        const concatenated = df1.concat(df2);

        expect(concatenated.toArray(), "Check initial state").to.eql([
            { Name: "Row 1", Id: 1 },
            { Name: "Row 2", Id: 2 }
        ]);

        // Generate a new series
        const generated = concatenated.generateSeries({
            NewId: row => row.Id
        });

        expect(generated.toArray(), "Check that the original values are preserved").to.eql([
            { Name: "Row 1", Id: 1, NewId: 1 },
            { Name: "Row 2", Id: 2, NewId: 2 }
        ]);

        expect(concatenated.toArray(), "Check that the original concatenated dataframe is unchanged").to.eql([
            { Name: "Row 1", Id: 1 },
            { Name: "Row 2", Id: 2 }
        ]);

        expect(df1.toArray(), "Check that the original dataframe df1 is unchanged").to.eql([{ Name: "Row 1", Id: 1 }]);
        expect(df2.toArray(), "Check that the original dataframe df2 is unchanged").to.eql([{ Name: "Row 2", Id: 2 }]);
    });

```

**Comment by ashleydavis** [comment]
Hi @ralphpw I've figured out the issue.

You don't have an explicit index on dataframes and merging them results in both rows have the same index. So when you generate a new series and merge it in, it doesn't merge the way you expect.

The simple solution is to either add an explicit index (maybe using id or datetime?), otherwise to get your test case working (thank you for the test case) I did a `resetIndex` after the concat, which makes the first row have index 0 and the second row have index 1 (instead of both rows having index 0): https://github.com/data-forge/data-forge-ts/blob/2d0f2c069fa6dd61433afcad437dddaae9e6677a/src/test/dataframe.concat.test.ts#L183

I know this confusing and if I ever build Data-Forge v2 I would like to revise the way indexes work so they make more sense.
