### ISSUE TITLE
[newbie question] Modus-operandi of a simple filtering case of DF needs some education

### ISSUE THREAD

**Issue by vtharmalingam** [data-forge/data-forge-ts#21]
Hello,

I have a very basic problem. As I am seasoned Pandas (python) programmer, I wanted to try out data-forge DF the moment I saw this one. Thank you so much for bringing this wonderful piece, and it had a lot of potential being part of JS echo system... 

But I had a basic starting thing to over come, and do not find that been talked in any of the blog/doc that I went through.  Surprising. here is my problem -

I constructed a DF using an array of objects.
`var df = new DataFrame( deposit_history );`

Then I tried to filter like this:
`var df2 = df.where( row => row.status === 'PG_FAILED' );`

Then I check what the content of df2 is... it is only null.
`DataFrame {configFn: , content: null}`

Later (after spending lot of time), I tried .toArray(), then I check df2 again,
`DataFrame {configFn: , content: Object}`

This behavior looks so odd to me, and maybe I am thinking like the 'where()' alone does not construct the resultant DF, and it looks like there is a method (probably like 'execute') is to be invoked after where. That I am missing. In the absence of that hypothetical method 'execute', when one calls toArray() that really executes the query-plan. Is that what us really going on. Would greatly appreciate if the right way is explained. Thanks in advance.

PS: here is one of the ways Python works:
`df[~df.order_type.str.contains('fb|foc|nfr|other')]`

or 

`df[ df['std_product_class'].str.contains('TB', case=False) ]`

Regards,
Tharma

**Comment by ashleydavis** [comment]
Hi Tharma, thanks for your feedback!

DataFrames in Data-Forge are only evaluated lazily. So you can't 'look' at the content of them without evaluating them.

So call toArray() or toRows() to evaluate the output.

You could also called bake(), then you can 'look' at the output, but be careful about using bake because it forces evaluation which can benefit or hurt performance depending on when you use it.

Eg

```
dfBaked = df.bake();
```

Hope that helps!

Please star the repo!

**Comment by vtharmalingam** [comment]
Yes, absolutely👍 
Thank you very much!

PS: starred the rep.
