### ISSUE TITLE
dropSeries is not a function.

### ISSUE THREAD

**Issue by thisisloze** [data-forge/data-forge-ts#25]
`    .dropSeries(['id', 'open', 'high', 'low', 'volume', 'startTime']) // Drop certain columns.
     ^

TypeError: dataForge.readFile(...).parseCSV(...).dropSeries is not a function`

My code looks like: 
`const dataForge = require('data-forge');
require('data-forge-fs');
require('data-forge-plot');

const df = dataForge.readFile('binance_btc_usdt_time_5m.csv')
    .parseCSV()
    .dropSeries(['id', 'open', 'high', 'low', 'volume', 'startTime']) // Drop certain columns.
    .then(df => {
        console.log(df.toString())
    })
    .catch(err => {
        console.log(err)
    });`

**Comment by ashleydavis** [comment]
Your problem is that you aren't letting the asynchronous function resolve before trying to call `dropSeries`.

The quickest fix for you is to call the synchronous version of readFile, that means replace `readFile` with `readyFileSync` as follows:

const dataForge = require('data-forge');
require('data-forge-fs');
require('data-forge-plot');

```
const df = dataForge.readFileSync('file...').parseCSV().dropSeries(....);
```

If you want to use the asynchronous readFile version then you need to use promises and chain a 'then' handler as follows:

```
dataForge.readFileSync('file...').parseCSV()
    .then(df => {
         df = df.dropSeries(....);
         // ... rest of your code goes here ...
    });
```

Otherwise you can also use async/await which is a bit more convenient than using promises:

let df = await dataForge.readFile('file...').parseCSV();
df = df.dropSeries(...);
