### ISSUE TITLE
Directly editing cell values in data frames

### ISSUE THREAD

**Issue by holwech** [data-forge/data-forge-ts#40]
Is there no way to edit cell values directly, similarly to how it's done in Pandas?

Example: `df['name1']['name2'] = 10`

I haven't found anything relevant in the documentation, so I assume there is no function for this. So then the question is, is there any way to modify data frames without having to rebuild whole frames/series every time a modification is done?

**Comment by holwech** [comment]
I discovered your section on immutability and I see that my question is maybe not that relevant then. That being said, I still haven't found an easy way to replace/modify a single value (and generating a new data frame based on that operation).

**Comment by ashleydavis** [comment]
As far as I recall I've never added the functionality you request.

Just because it's immutable doesn't mean it can't work, it just means any modification to the data returns a new dataframe. Some extra care must therefore be taken to ensure it does so with good memory performance.

I could easily imagine a `set` function to do this but I have very little time at the moment with my current commitments.

Please feel free to try adding some code and submit a pull request. Even if your 1st pass doesn't have good performance that's ok, maybe then I could give you some guidance on how to improve it.

**Comment by holwech** [comment]
Ok, this library might not be right one for me, as I need to do in-place mutations to the data frame. I made a semi-crap `set` function for anyone who comes across this and needsset function for this library:

```typescript
const setDataframeValue = (df: dataForge.IDataFrame<string, any>, rowKey: string, columnKey: string, value: number) => {
  const pairs = col.getSeries(columnKey).toPairs();
  const newArray = [];
  for (const [i, el] of array.entries()) {
    if (el[0] === rowKey) {
      pairs[i][1] = value;
      newArray.push(value);
    } else {
      newArray.push(el[1]);
    }
  }
  const newSeries = new dataForge.Series({ 
    index: df.getIndex(),
    values: newArray,
  });
  return df.withSeries({
    [columnKey]: newSeries,
  });
```

**Comment by ashleydavis** [comment]
Cool thanks, that gives me a place to start.  Could submit an example of use as well? If you can submit code that works (eg you tested it) then I'll make the effort to integrate it.

**Comment by ashleydavis** [comment]
I've scheduled this for DF version 2, unless someone else wants to implement in version 1 first.
