### ISSUE TITLE
Project setup failed

### ISSUE THREAD

**Issue by rwilliams-home** [data-forge/data-forge-ts#56]
Just installed DFN, tried to run the intro notebook and a big red dialog announced:

Project setup failed, see log file for full details.
Error: spawn[1]: npm ERR! code E403
npm ERR! 403 Forbidden: @types/request-promise@^4.1.44
npm ERR! A complete log of this run can be found in:
npm ERR! /Users/rwilliams/Library/Application Support/data-forge-notebook/npm-cache/_logs/2019-11-15T05_51_22_276Z-debug.log
Error code: 1

Relevant log entry:
24 verbose stack Error: 403 Forbidden: @types/request-promise@^4.1.44
24 verbose stack     at fetch.then.res (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
24 verbose stack     at tryCatcher (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
24 verbose stack     at Promise._settlePromiseFromHandler (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
24 verbose stack     at Promise._settlePromise (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
24 verbose stack     at Promise._settlePromise0 (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
24 verbose stack     at Promise._settlePromises (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
24 verbose stack     at Async._drainQueue (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
24 verbose stack     at Async._drainQueues (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
24 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
24 verbose stack     at runCallback (timers.js:705:18)
24 verbose stack     at tryOnImmediate (timers.js:676:5)
24 verbose stack     at processImmediate (timers.js:658:5)
25 verbose cwd /Applications/Data-Forge Notebook.app/Contents/examples
26 verbose Darwin 18.7.0
27 verbose argv "/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/bin/node" "/Applications/Data-Forge Notebook.app/Contents/nodejs/v10.15.3/lib/node_modules/npm/bin/npm-cli.js" "install" "--bin-links" "false" "--scripts-prepend-node-path" "true" "--cache" "/Users/rwilliams/Library/Application Support/data-forge-notebook/npm-cache" "--prefer-offline" "--no-audit"
28 verbose node v10.15.3
29 verbose npm  v6.4.1
30 error code E403
31 error 403 Forbidden: @types/request-promise@^4.1.44
32 verbose exit [ 1, true ]

**Comment by ashleydavis** [comment]
Hi Richard, sorry to hear you are having problems and thanks so much for your support!

This is the issue tracker for Data-Forge which is my open source library for data analysis and it sounds like your problem is with Data-Forge Notebook which is a different product. Just letting you know that that you'll get quicker support from me on Data-Forge Notebook if you email me direct or message me in Slack (I'll invite you to the Slack channel in a moment).

In any case this sounds like you might be trying to do an npm install through a proxy:

    https://stackoverflow.com/questions/11773509/npm-behind-a-proxy-fails-with-status-403

Data-Forge Notebook automatically installs npm modules for you (so you don't have to manually install them) and for some reason it's failing on that so it could be a proxy, firewall or something else like that.

This is the wrong channel to discuss anyway. I'll invite you to the Slack channel, we'll take it from there and I'm sure we'll get it solved quickly.

Cheers
Ashley Davis
