### ISSUE TITLE
Write DataFrame as CSV file without headers.

### ISSUE THREAD

**Issue by eparizzi** [data-forge/data-forge-ts#68]
Readme suggests the following code to write a DataFrame out as a CSV file.

```javascript
  dataFrame
    .asCSV()
    .writeFileSync("output.csv");
```

But this method doesn't allow any option to set whether we want to include the headers or not.

Looking at the source code I see there's a [DataFrame.toCSV(options?: ICSVOutputOptions)](https://github.com/data-forge/data-forge-ts/blob/7b6287baca46cec5384700d1155049428d932d39/src/lib/dataframe.ts#L2415) which takes an `options` argument which can be used to set `header: false` and exclude the headers.

It's not clear why there are 2 different methods, `toCSV()` and `asCSV()` (which is actually in `data-forge-fs`). My guess is that the first one is used to just get a string representation and the former is optimized to be written out as a file.

Assuming my guess is correct, shouldn't `asCSV()` also accept an `ICSVOutputOptions` parameter?

**Comment by ashleydavis** [comment]
There are two functions because normal Data-Forge doesn't support writing files (it can run in the browser as well as Node.js).

So normal Data-Forge has `toCSV` so that you can generate CSV data from your dataframe.

Data-Forge FS is what adds file system capability to Data-Forge so that you can read and write files in Node.js.

asCSV().writeFile() actually calls toCSV under the hood.

It seems to be an oversight that you can't pass options to as CSV! I actually can't believe I've never noticed that myself so thanks for pointing it out.

**Comment by ashleydavis** [comment]
I've published version 0.0.8 of data-forge-fs. You can now pass options to asCSV. Pls let me know if that works for you!

**Comment by ashleydavis** [comment]
@eparizzi is it working ok for you now?

**Comment by eparizzi** [comment]
Yes, thank you!
